// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  oauthUrl: '', // Added proxy in nginx
  serverUrl: 'https://api.github.com',
  clientId: '92bded2cfd66ea416d18',
  scope: 'user,public_repo',
  clientSecret: 'bed77c79516309110e5c03ccf757f385530e5940',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
